image: rust

stages:
  - test
  - publish

before_script:
  - apt-get update
  - apt-get install -y libclang-3.9-dev libspeechd-dev
  - export CPATH=/usr/lib/llvm-3.9/lib/clang/3.9.1/include/

test:
  stage: test
  script:
  - cargo build
  - rustup target add wasm32-unknown-unknown
  - cargo build --target wasm32-unknown-unknown

publish:
  stage: publish
  script:
  - cargo login $CARGO_TOKEN
  - cargo package
  - cargo publish
  only:
  - tags
