[package]
name = "tts"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2018"

[dependencies]
log = "0.4"

[dev-dependencies]
env_logger = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
speech-dispatcher = "0.2"
