[tasks.build-android-example]
script = [
    "cd examples/android",
    "./gradlew assembleDebug",
]

[tasks.run-android-example]
script = [
    "cd examples/android",
    "./gradlew runDebug",
]

[tasks.log-android]
command = "adb"
args = ["logcat", "RustStdoutStderr:D", "*:S"]