[package]
name = "tts_winrt_bindings"
version = "0.2.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
description = "Internal crate used by `tts`"
license = "MIT"
edition = "2018"

[dependencies]
winrt = "0.7"

[build-dependencies]
winrt = "0.7"
