name: Test

on:
  push:
  pull_request:

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev
          cargo build --release
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          choco install -y llvm
          cargo build --release
