name: Test

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev
        if: ${{ runner.os == 'Linux' }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --examples

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --examples --target wasm32-unknown-unknown

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-ios x86_64-apple-ios
          profile: minimal
          toolchain: stable
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-lipo
      - uses: actions-rs/cargo@v1
        with:
          command: lipo
          args: --all-features --examples
